### PR TITLE
Upgrades and travis

### PR DESCRIPTION
**Pull request by maikelmclauflin**

### CODE REVIEW

**Comment by maikelmclauflin** [comment]
Seems like i'm having trouble getting tests to pass even locally. i'm just trying to test that bottleneck has been applied in my project and it seems to fail when i wrap.

**Comment by SGrondin** [comment]
See my response in the Issue.

Regarding the PR itself, it will be more complicated than this, since running `npm run test-all` requires a Redis server. If all you want to do is run the simple local tests, you can do `npm test`.

It's also important to keep the number of dependencies at 0. I'm not sure I understand where minimatch is needed.

**Comment by SGrondin** [comment]
Also, right now it needs the redis server to run on `localhost` with the default port. If that needs to change I'll set up support for that this weekend.

**Comment by SGrondin** [comment]
At a glance it's looking really good! I'll have time this weekend to run it, validate it and merge it.

This is exciting 😄

**Comment by maikelmclauflin** [comment]
looks like one of your deps needs v8 https://github.com/airbnb/node-memwatch/blob/master/package.json#L7

**Comment by maikelmclauflin** [comment]
seems like there's also a couple of race conditions being hit. had to restart build a couple of times from failures.

**Comment by SGrondin** [comment]
Some of the tests are written as race conditions: a certain thing has to happen within a certain time for the test to succeed. Those times assume there is no latency to reach the redis server. I was busy with another project today and didn't have the time to look into this 😞 I'll have time tomorrow. One thing I noticed is we'll have to add pass the redis url for all the ioredis/redis tests, not just that one ioredis cluster test. It can be done [here](https://github.com/SGrondin/bottleneck/blob/master/test/context.js#L19-L24), I'll do it tomorrow unless you get to it first.

**Comment by SGrondin** [comment]
Merged! 🎉 

You can see the changes I've made [here](https://github.com/SGrondin/bottleneck/commit/149730ec692d6fceb42c42cfdb161396cd1b432e). Thank you for your contribution!

**Comment by maikelmclauflin** [comment]
fair enough, and happy to help. hope it makes development easier.

**Pull request merged**
