### PR TITLE
Allow wrapped functions to inherit original "this" context

### PR DESCRIPTION
**Pull request by elliot-nelson**
### PURPOSE

Allow the "this" argument to be inherited when calling a function wrapped by a limiter.  This allows more natural usage of limits when applied to modules or class methods, e.g.:

    var object = {
        value: "Hello World",
        hello: limit.wrap(function () {
            return this.value;
        })
    };

    // When calling `object.hello()`, `this` = `object`
    object.hello().then(console.log);

### DETAILS

The majority of ways you can schedule a task can't inherit `this`, because we don't have that context.  That includes `schedule`, `submit`, and the `withOptions` variant of a wrapped function.  But, when calling a wrapped function directly, we _do_ have that context, so we might as well inherit it.

This is especially useful for wrapping class (prototype) methods, so I included a test to make that use case clear.

(There may also be a better/more appropriate place to make this fix, this is just my suggestion!)

### CODE REVIEW

**Comment by elliot-nelson** [comment]
Hmm, worked on my machine :).  I'll see if I can make heads or tails of the failures in the Travis build.

**Comment by SGrondin** [comment]
Travis has different latencies than local development and sometimes needs to be re-run. I'm slowly tweaking the tests to make them more resilient.

Very nice tests! I like the feature a lot. I think it would also work with `withOptions`, same changes: `->` instead of `=>` and `fn.bind(this)`? That would minimize the inconsistencies between the different ways to add a job.

**Comment by SGrondin** [comment]
I'd be interested to hear your ideas on how to improve the Readme when it comes to contexts. In my experience, most JS devs simply do not understand how it works: prototypes, classes, `function` vs `=>`, etc. I recently added a small paragraph to the 'Gotchas' section due to how frequent those mistakes are.

**Comment by elliot-nelson** [comment]
I don't think it'll work for options unfortunately, only because of the calling syntax:

    object.fn.withOptions({ });

In this case `wrapped.withOptions`, even if we did bind, would receive `fn` (a prototype method) and not `object`.  Not sure if there is a good way around that one.

Good points on readme, I'll think about it!

**Comment by SGrondin** [comment]
I'll try it out when I have time this weekend, I think I can use some `apply()` magic to make it work.

**Comment by elliot-nelson** [comment]
I think you have different use cases here.  The use case where options actually matter is probably the one where you are using bottleneck like it is a job scheduler, maybe even with redis, giving jobs IDs and priorities, etc.

With my use case, which is more just "hey, I don't want to spam AWS", I can get away with something like this:

    myModule.downloadFile = new Bottleneck({ maxConcurrent: 10 }).wrap((bucket, key, options) => {
        // basic AWS SDK call here
    });

So the "lack" of options isn't a big deal.  If I really wanted to use options and keep context, that's when the caller has to step in:

    // With bind
    myModule.downloadFile.withOptions.bind(myModule)({}, bucket, key);

    // Or with call
    myModule.downloadFile.withOptions.call(myModule, {}, bucket, key);

One approach could be a new method that takes options for "the next call", which then resets them.  In fact, you could even support a "permanent" option set and a "next call" variant... Might look like this:

    // No options
    object.fn().then(...);

    // Permanently set expiration for this fn
    object.fn.setOptions({ expiration: 1800 });
    object.fn().then(...);
    object.fn().then(...);

    // Set ID and Priority only for the _next_ call
    object.fn.nextOptions({ priority: 1, id: uuid });
    object.fn().then(...);

    // This call has no id or priority.  Expiration still exists.
    object.fn().then(...);

For `schedule` and `submit`, I think nothing needs to change -- those APIs already make plenty of sense when your use case is a more robust "queue" of tasks.  I think the easiest advice for executing any/all class methods there is just the arrow function:

    limiter.schedule({ priority: 1 }, () => object.fn()).then(result => ...);

**Comment by SGrondin** [comment]
>With my use case, which is more just "hey, I don't want to spam AWS", I can get away with something like this:
>So the "lack" of options isn't a big deal. If I really wanted to use options and keep context, that's when the caller has to step in:

You're totally right, I'm convinced.

>One approach could be a new method that takes options for "the next call", which then resets them. In fact, you could even support a "permanent" option set and a "next call" variant... Might look like this:

I don't think this is worth the complexity and added confusion.

I'm merging this and I'll play with it this weekend and release it soon.

**Comment by SGrondin** [comment]
This has been released as part of 2.16.2

**Pull request merged**
