### PR TITLE
Add type definitions for bottleneck/light

### PR DESCRIPTION
**Pull request by copperwall**
Hey there, octokit/plugin-retry.js uses `bottleneck/light` for ratelimiting, but there's a little bit of trouble importing types when using `bottleneck/light` over the main `bottleneck` import.

I did some testing and adding a `light.d.ts` definition file with existing namespace and class types but under a `bottleneck/light` module lets typescript find the types for the light import.

I noticed that the existing type definitions were using EJS templates, so I move the namespace and class type definitions to a shared EJS template and included that in both the bottleneck.d.ts.ejs and light.d.ts.ejs template files.

This fixes the issue in https://github.com/octokit/plugin-retry.js/pull/110, but I'm open to suggestions if there's a better way to do this!

### CODE REVIEW

**Comment by SGrondin** [comment]
I'll make a new release tonight

**Comment by gr2m** [comment]
Hey Simon, could you do the release please?

**Comment by oscard0m** [comment]
Hi @SGrondin, I was walking through existing open issues in Octokit and I arrived to an issue which depends on these changes to be released, what's the status of `bottleneck` project? Can we help you with something?

Thanks for your time and please let us know if you need help.

**Comment by gr2m** [comment]
@SGrondin it looks like there is still no new release. Could you please do a new release that includes this fix?

**Comment by lmk123** [comment]
I merged this PR into my fork and published it to npm.

npm: https://www.npmjs.com/package/@hcfy/bottleneck

Source code: https://github.com/hcfyapp/bottleneck

Install:

```
npm i @hcfy/bottleneck
```

Then import:

```js
import Bottleneck from '@hcfy/bottleneck/light'
```

**Pull request merged**
